In [1]:
import sys
print(sys.executable)

c:\Users\ars5893\.calendar_project\.venv2\Scripts\python.exe

In [2]:
import numpy as np
import pandas as pd
print(pd.__version__)

3.0.1

In [80]:
df = pd.read_csv('03.01.2026-04.01.2026.CSV')
print(df.shape)
print(np.sum(df.isnull()))
df.head()

(112, 22)
598

,Subject,Start Date,Start Time,End Date,End Time,All day event,Reminder on/off,Reminder Date,Reminder Time,Meeting Organizer,...,Meeting Resources,Billing Information,Categories,Description,Location,Mileage,Priority,Private,Sensitivity,Show time as
0,"BLCK_ST_101: Fighting Apartheid, Locally and G...",2/5/2026,3:30:00 PM,2/5/2026,4:45:00 PM,False,False,2/5/2026,3:15:00 PM,NaN,...,NaN,NaN,NaN,Date: 02/05/2026\r\n\r\nTime: 3:30PM-4:50 PM\r...,Katz classroom,NaN,Normal,False,Normal,1
1,ART_HIST 232: Introduction to the History of A...,2/27/2026,12:00:00 PM,2/27/2026,1:50:00 PM,False,False,2/27/2026,11:45:00 AM,NaN,...,NaN,NaN,NaN,Date: 02/27/2026\r\n\r\nTime: 12:00-1:50 PM\r\...,Katz classroom,NaN,Normal,False,Normal,1
2,ART_HIST 232: Introduction to the History of A...,2/13/2026,9:00:00 AM,2/13/2026,1:00:00 PM,False,False,2/13/2026,8:45:00 AM,NaN,...,NaN,NaN,NaN,Date: 02/13/2026\r\n\r\nTime: 9:00AM-1:00 PM\r...,Katz classroom,NaN,Normal,False,Normal,1
3,ART_HIST 330: Renaissance Worlds,2/13/2026,1:00:00 PM,2/13/2026,2:00:00 PM,False,False,2/13/2026,12:45:00 PM,NaN,...,NaN,NaN,NaN,Date: 02/13/2026\r\n\r\nTime: 1:00PM-2:00 PM\r...,Katz classroom,NaN,Normal,False,Normal,1
4,ENG 377: Latinx Feminism,2/18/2026,9:30:00 AM,2/18/2026,10:45:00 AM,False,False,2/18/2026,9:15:00 AM,NaN,...,NaN,NaN,NaN,Date: 02/18/2026\r\n\r\nTime: 9:30-10:50 AM\r\...,Katz classroom,NaN,Normal,False,Normal,1

In [ ]:
# merge/concatenate/transpose
# datetime
# missing values
# convert to word
""" 
first get the df to look good and proper, then i can learn how to turn it into word doc with proper formatting
"""

In [ ]:
# filter for week?
"""
start = '2026-02-05'
end = '2026-02-12'

df = df[(df['start_dt'] >= start) & (df['start_dt'] < end)]

df['date_str'] = df['start_dt'].dt.strftime('%A, %B, %d')
df['time_str'] = (df['start_dt']).dt.strftime('%-I:%M %p') + ' - ' + df['end_dt'].dt.strftime('%-I:%M %p') # does this need em dash
"""

In [81]:
from docx import Document
from datetime import datetime

cols = ['Subject', 'Start Date', 'Start Time', 'End Time', 'Description', 'Location']
df = df[cols]

df['start_dt'] = pd.to_datetime(df['Start Date'] + ' ' + df['Start Time'])
df['end_dt'] = pd.to_datetime(df['Start Date'] + ' ' + df['End Time'])
df = df.drop(['Start Date', 'Start Time', 'End Time'], axis = 1)

df = df.sort_values('start_dt')

df['Subject'] = df['Subject'].str.replace('\n', ' ').str.strip()
mask = ~df['Subject'].str.strip().str.upper().str.startswith(('CANCELED', 'AUTOMATED'))
df = df[mask]

df['Description'] = df['Description'].str.replace('\r\n', ' ').str.strip()
zoom_strings = ['urldefense', 'zoom.com', 'zoom.us']
pattern = '|'.join(zoom_strings) # what?
df['Description'] = df['Description'].mask(df['Description'].str.contains(pattern, case=False), '')
df['Location'] = df['Location'].mask(df['Location'].str.contains(pattern, case=False), '')

df

C:\Users\ars5893\AppData\Local\Temp\ipykernel_29112\866908692.py:7: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['start_dt'] = pd.to_datetime(df['Start Date'] + ' ' + df['Start Time'])
C:\Users\ars5893\AppData\Local\Temp\ipykernel_29112\866908692.py:8: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['end_dt'] = pd.to_datetime(df['Start Date'] + ' ' + df['End Time'])

,Subject,Description,Location,start_dt,end_dt
12,AMER_ST 310: The Military-Industrial Complex,Date: 02/02/2026 Time: 2:00-3:20 PM Type of ...,Katz classroom,2026-02-02 14:00:00,2026-02-02 15:20:00
27,All Staff Meeting (Winter 2026),,,2026-02-04 11:00:00,2026-02-04 12:00:00
81,Self Guided: ENG 105: Who Are Museums For?,Date: 02/04/2026 Time: 12:30 - 1:50PM Type ...,All galleries,2026-02-04 12:30:00,2026-02-04 13:50:00
82,AH 403 student visit,Date: 02/04/2026 Time: 2:00PM-3:00 PM Type o...,Katz classroom,2026-02-04 14:00:00,2026-02-04 15:00:00
23,Living Room Weekly Coffee,Date: Every Wednesday from 3-5pm Time: 2:15PM...,Block lobby,2026-02-04 14:15:00,2026-02-04 17:15:00
...,...,...,...,...,...
79,ART_HIST 232: Introduction to the History of A...,Date: 02/27/2026 Time: 12:00PM-1:50PM Type o...,Katz classroom,2026-02-27 12:00:00,2026-02-27 13:50:00
1,ART_HIST 232: Introduction to the History of A...,Date: 02/27/2026 Time: 12:00-1:50 PM Type of...,Katz classroom,2026-02-27 12:00:00,2026-02-27 13:50:00
7,BMSA Weekly Training,Date: Fridays during the academic year Time: ...,Conference Room,2026-02-27 15:00:00,2026-02-27 17:00:00
63,Prospective Art History Graduate Student visit,Date: 02/27/2026 Time: 3:00-4:00 PM Type of ...,galleries / Living Room / TBD,2026-02-27 15:00:00,2026-02-27 16:00:00
19,PUBLIC PROGRAM: BMSA Art Talks! Hamdia Traoré,Date: 02/28/2026 Time: 12:30PM-1:30PM Type o...,main gallery,2026-02-28 12:30:00,2026-02-28 13:30:00

In [69]:
import textwrap

for idx, desc in enumerate(df['Description'].head(30)):
    print(f"--- Row {idx} ---")
    print(textwrap.fill(desc, width=80))
    print()

--- Row 0 ---
Date: 02/02/2026  Time: 2:00-3:20 PM  Type of Event: Class visit  Name of Group:
AMER_ST 310: The Military-Industrial Complex  Location: Katz Classroom  Internal
Contact Person(s): Essi Rönkkö  External Contact Person(s): Keva X. Bui
<kxbui@northwestern.edu>  Guests Expected: TBD  Taking Attendance (Y/N): Y
Attendance Total:  Notes: Please have bins available in the lobby.

--- Row 1 ---
<https://urldefense.com/v3/__https://zoom.com__;!!Dq0X2DkFhyF93HkjWTBQKhk!S5Ji2l
iQrASVmZD869S_5jJzFVIlGjE4GWh5KolDP2WN002aNaOfrptUSvEdUXM0EaD2MWdl0HtyyI8bPA1Xo3
FxMEjukd7MmjrhZ4CbFws6XF823iulW2w$>      Hi there,        Christopher Forrester
is inviting you to a scheduled Zoom meeting.     Join Zoom Meeting <https://urld
efense.com/v3/__https://northwestern.zoom.us/j/96867121232?from=addon__;!!Dq0X2D
kFhyF93HkjWTBQKhk!S5Ji2liQrASVmZD869S_5jJzFVIlGjE4GWh5KolDP2WN002aNaOfrptUSvEdUX
M0EaD2MWdl0HtyyI8bPA1Xo3FxMEjukd7MmjrhZ4CbFws6XF82A7Jmt5k$>      One tap mobile:
US: +13092053325,,96867121232# <tel:+13092053325,,96867121232#>  or
+13126266799,,96867121232# <tel:+13126266799,,96867121232#>          Meeting
URL:   https://northwestern.zoom.us/j/96867121232?from=addon <https://urldefense
.com/v3/__https://northwestern.zoom.us/j/96867121232?from=addon__;!!Dq0X2DkFhyF9
3HkjWTBQKhk!S5Ji2liQrASVmZD869S_5jJzFVIlGjE4GWh5KolDP2WN002aNaOfrptUSvEdUXM0EaD2
MWdl0HtyyI8bPA1Xo3FxMEjukd7MmjrhZ4CbFws6XF82A7Jmt5k$>           Meeting ID:
968 6712 1232     Join by Telephone      For higher quality, dial a number based
on your current location.       Dial:  +1 309 205 3325 US +1 312 626 6799 US
(Chicago) +1 301 715 8592 US (Washington DC) +1 305 224 1968 US +1 646 931 3860
US +1 929 436 2866 US (New York) +1 689 278 1000 US +1 719 359 4580 US +1 253
205 0468 US +1 253 215 8782 US (Tacoma) +1 346 248 7799 US (Houston) +1 360 209
5623 US +1 386 347 5053 US +1 507 473 4847 US +1 564 217 2000 US +1 669 444 9171
US +1 669 900 6833 US (San Jose)    Meeting ID:    968 6712 1232
International numbers <https://urldefense.com/v3/__https://northwestern.zoom.us/
u/a8l2pMmL9__;!!Dq0X2DkFhyF93HkjWTBQKhk!S5Ji2liQrASVmZD869S_5jJzFVIlGjE4GWh5KolD
P2WN002aNaOfrptUSvEdUXM0EaD2MWdl0HtyyI8bPA1Xo3FxMEjukd7MmjrhZ4CbFws6XF82i6k6_sw$
>       Join from an H.323/SIP room system     H.323:         144.195.19.161 (US
West) 206.247.11.121 (US East) 221.122.88.195 (Mainland China) 115.114.131.7
(India Mumbai) 115.114.115.7 (India Hyderabad) 159.124.15.191 (Amsterdam
Netherlands) 159.124.47.249 (Germany) 159.124.104.213 (Australia Sydney)
159.124.74.212 (Australia Melbourne) 170.114.134.121 (Hong Kong SAR)
170.114.180.219 (Singapore) 64.211.144.160 (Brazil) 159.124.132.243 (Mexico)
159.124.168.213 (Canada Toronto) 159.124.196.25 (Canada Vancouver)
170.114.194.163 (Japan Tokyo) 147.124.100.25 (Japan Osaka)        Meeting ID:
968 6712 1232     SIP:  96867121232@zoomcrc.com
________________________________   Access the BLOCK-STAFF Home Page and Archives
<https://LISTSERV.IT.NORTHWESTERN.EDU/cgi-bin/wa.exe?A0=BLOCK-STAFF>
Unsubscribe from the BLOCK-STAFF List <https://LISTSERV.IT.NORTHWESTERN.EDU/cgi-
bin/wa.exe?TICKET=NzM5NjYxIHJvY2lvLm9sYXNpbWJvQE5PUlRIV0VTVEVSTi5FRFUgQkxPQ0stU1
RBRkYgIBFuknUwp5md&c=SIGNOFF>

--- Row 2 ---
Date: 02/04/2026  Time:  12:30 - 1:50PM  Type of Event:  Class  Name of Group:
Expository Writing (105-0-21) Who Are Museums For?  Location: All galleries
Internal Contact Person(s): Erin  External Contact Person(s): Alice Boone
Guests Expected:  12  Taking Attendance (Y/N): Y  Attendance Total:  Notes:
Self-guided class visit from 12 Northwestern students; attending for a class
assignment.

--- Row 3 ---
Date: 02/04/2026  Time: 2:00PM-3:00 PM  Type of Event: student visit  Name of
Group: ART_HIST 403 Object and Materials Seminar  Location: Katz Classroom
Internal Contact Person(s): Corinne Granof  External Contact Person(s): Joitree
Alam; Antawan Byrd  Guests Expected: 2  Taking Attendance (Y/N): Y  Attendance
Total:  Notes:

--- Row 4 ---
Date: Every Wednesday from 3-5pm  Time: 2:15PM-5:15PM  Type of Event: Reception
Name of Group: Living Room Weekly Coffee   Location: Block lobby   Internal
Contact Person(s): Erin and Chris  External Contact Person(s):  N/A  Guests
Expected: N/A  Taking Attendance (Y/N): N  Attendance Total:   Notes: VS –
please set up an 8 ft table near the magazine rack each Wednesday by 2:15pm.
Compass Catering will drop off coffee/tea service and a linen between
2:30-2:45pm, and return to pick this up at 5:00pm. VS, please also take away the
bars and leave in the Engagement office (we will not serve these to the public)
We will not serve coffee on Wed Mar 25 (Spring Break). We will have an extra
Living Room coffee on Thurs, Jan 22 from 3-5pm in addition to the weekly coffee
on Wed, Jan 21.   The last coffee of Spring Quarter will be on Wed, Apr 1; the
Living Room will close on Sun, Apr 12. Contact Chris or Erin with questions.

--- Row 5 ---
Date: 2/4/2026  Time: 4:00PM-5:00PM  Type of Event: Eng-led (BMSA training)
Name of Group: BMSA Seminar  Location: Conference Room   Internal Contact
Person(s): Erin Northington   External Contact Person(s): N/A  Guests Expected:
20  Taking Attendance (Y/N): N  Attendance Total:  Notes:

--- Row 6 ---
Date: 02/05/2026  Time: 3:30PM-4:50 PM  Type of Event: Class visit  Name of
Group: BLCK_ST_101: Fighting Apartheid, Locally and Globally  Location: Katz
Classroom  Internal Contact Person(s): Essi  External Contact Person(s): Martha
Biondi <m-biondi@northwestern.edu>  Guests Expected: TBD (likely 16)  Taking
Attendance (Y/N): Y  Attendance Total:  Notes: Please have bins available in the
lobby.

--- Row 7 ---
Date: 02/06/2026  Time: 10:45AM-12:00PM  Type of Event: Class visit  Name of
Group: ART_HIST 395: Displaying Empire  Location: Katz Classroom, Leffmann
Gallery  Internal Contact Person(s): Essi  External Contact Person(s): Yuthika
Sharma <yuthika.sharma@northwestern.edu>  Guests Expected: TBD (ca. 11)  Taking
Attendance (Y/N): Y  Attendance Total:  Notes: Please have bins available in the
lobby. NOTE: We will not need the galleries the entire time. (Likely only around
10:45-11am)

--- Row 8 ---
Date: Fridays during the academic year  Time: 3:00PM-5:00PM  Type of Tour: Eng-
led  Name of Group: 2025-2026 BMSA Weekly Meeting  Location: Conference Room and
Galleries  Block Contact Person(s): Erin and Isabella  External Contact
Person(s): Erin and Isabella  Guests Expected: 21  Taking Attendance (Y/N): N
Attendance Total:  Notes:

--- Row 9 ---
Date: 02/07/2026  Time:  11:00-12:00pm  Type of Event:  VIP visit  Name of
Group: VIP artist visit: Teresa Montoya  Location: Main galleries  Internal
Contact Person(s): Erin/Margaret  External Contact Person(s): Teresa Montoya
Guests Expected:  1-2  Taking Attendance (Y/N): N  Attendance Total:  Notes:
Kathleen will greet artist Teresa Montoya and walk through the exhibition with
her at 11:00am.

--- Row 10 ---
Date: 02/07/26   Time:1-1:30pm; Engagement setting up auditorium starting
11:30am   Type of Event: tech check  Name of Group: TECH CHECK: Teresa Montoya
in Conversation  Location: auditorium    Internal Contact Person(s): Margaret,
Ben   External Contact Person(s):  N/A  Guests Expected: NA  Taking Attendance
(Y/N): N  Attendance Total:  Notes:

--- Row 11 ---
Date: 02/07/26   Time: 2:00-3:30PM  Type of Event: Public Program  Name of
Group: Teresa Montoya in Conversation  Location: Block lobby, Block Auditorium
Internal Contact Person(s): Margaret, Isabella, Erin  External Contact
Person(s):  N/A  Guests Expected: 140  Taking Attendance (Y/N): Y  Attendance
Total:  Notes:  11:30am — Engagement staff arriving to The Block to set-up
11:45am — food for Block staff arrives; needs to be moved to conference room /
BMSAs arrive  12pm — museum opens to the public / Sean's team photographing in
the galleries  (FYI at 12pm, there's also a private luncheon occurring at
Norris, if folks ask you)   1-1:30pm — tech check in auditorium with speakers,
Margaret, and Ben 1:30pm — auditorium doors open to public/Engagement to confirm
2-3:30pm — public program  3pm — Compass arrives to set up reception ** VS: can
you help us set up the tables for this? Isabella will check-in with you all on
this, day-of 3:30-4:30pm — public reception  anywhere from 4:15-5pm — Compass
arrives for reception breakdown  5pm — museum closes

--- Row 12 ---
Date: 02/07/26   Time: 3:30-4:30PM  Type of Event: reception  Name of Group:
RECEPTION: Teresa Montoya in Conversation  Location: Block lobby   Internal
Contact Person(s): Margaret, Isabella, Erin  External Contact Person(s):  N/A
Guests Expected: 140  Taking Attendance (Y/N): N  Attendance Total:  Notes:  3pm
— Compass arrives to set up reception  3:30-4:30pm — public reception  anywhere
from 4:15-5pm — Compass arrives for reception breakdown  5pm — museum closes

--- Row 13 ---
Date: 02/08/2026 Time: 2:00PM-3:00PM Type of Event: public program — BMSA Art
Talks  Name of Group: BMSA Art Talks! Tó Łisto Location: Main Gallery  Internal
Contact Person(s): BMSAs, Isabella, Erin, Margaret  External Contact Person(s):
NA  Guests Expected: 25 max  Taking Attendance (Y/N): Y Attendance Total: Notes:

--- Row 14 ---
Date: 02/09/2026  Time: 11:00AM-12:00PM  Type of Event: Faculty/student visit
Name of Group: ART_HIST 403 Object and Materials Seminar  Location: Katz
Classroom  Internal Contact Person(s): Corinne Granof  External Contact
Person(s): Yuthika Sharma, yuthika.sharma@northwestern.edu
<mailto:yuthika.sharma@northwestern.edu> , and Maria Kokkori,
maria.kokkori1@northwestern.edu <mailto:maria.kokkori1@northwestern.edu>
Guests Expected: 2-3  Taking Attendance (Y/N): Y  Attendance Total:  Notes:

--- Row 15 ---
Date: 02/09/2026  Time: 12:30PM-1:50 PM  Type of Event: Class visit  Name of
Group: ENG 274: Introduction to Native American and Indigenous Literatures
Location: Katz Classroom  Internal Contact Person(s): Essi  External Contact
Person(s): Mariajose Rodriguez Pliego
<mariajose.rodriguezpliego@northwestern.edu>  Guests Expected: 21  Taking
Attendance (Y/N): Y  Attendance Total:  Notes: Please have bins available in the
lobby.

--- Row 16 ---
Date: 02/10/2026  Time: 12:30PM-1:50 PM  Type of Event: Class visit  Name of
Group: FRENCH 201: Les Formes du mal  Location: Katz Classroom  Internal Contact
Person(s): Essi Rönkkö  External Contact Person(s): Cynthia Nazarian
<nazarian@northwestern.edu <mailto:nazarian@northwestern.edu> >  Guests
Expected: 7  Taking Attendance (Y/N): Y  Attendance Total:  Notes: Please have
bins available in the lobby.

--- Row 17 ---
Date: 02/10/2026  Time: 4:00PM-5:00 PM  Type of Event: Campus/co-curricular
visit  Name of Group: NU Athletics  Location: Katz Classroom  Internal Contact
Person(s): Erin Northington   External Contact Person(s): Maria Elena Sanchez
maria.sanchez@northwestern.edu <mailto:maria.sanchez@northwestern.edu>   Guests
Expected: 4-8  Taking Attendance (Y/N): Y  Attendance Total:  Notes: Please have
bins available in the lobby.

--- Row 18 ---
The Winter Quarter Office of the Provost all-staff meeting will be held from
9-10 a.m. on February 11 in McCormick Auditorium in the Norris University
Center. Coffee, tea, and light breakfast fare will be available beginning at
8:45 a.m. inside the auditorium. We look forward to seeing you there!     ***
8:45am: Coffee, tea, and light breakfast fare available  9:00am: Program begins
10:00am: Program concludes

--- Row 19 ---


--- Row 20 ---
<https://urldefense.com/v3/__https://zoom.com__;!!Dq0X2DkFhyF93HkjWTBQKhk!S5Ji2l
iQrASVmZD869S_5jJzFVIlGjE4GWh5KolDP2WN002aNaOfrptUSvEdUXM0EaD2MWdl0HtyyI8bPA1Xo3
FxMEjukd7MmjrhZ4CbFws6XF823iulW2w$>      Hi there,        Christopher Forrester
is inviting you to a scheduled Zoom meeting.     Join Zoom Meeting <https://urld
efense.com/v3/__https://northwestern.zoom.us/j/96867121232?from=addon__;!!Dq0X2D
kFhyF93HkjWTBQKhk!S5Ji2liQrASVmZD869S_5jJzFVIlGjE4GWh5KolDP2WN002aNaOfrptUSvEdUX
M0EaD2MWdl0HtyyI8bPA1Xo3FxMEjukd7MmjrhZ4CbFws6XF82A7Jmt5k$>      One tap mobile:
US: +13092053325,,96867121232# <tel:+13092053325,,96867121232#>  or
+13126266799,,96867121232# <tel:+13126266799,,96867121232#>          Meeting
URL:   https://northwestern.zoom.us/j/96867121232?from=addon <https://urldefense
.com/v3/__https://northwestern.zoom.us/j/96867121232?from=addon__;!!Dq0X2DkFhyF9
3HkjWTBQKhk!S5Ji2liQrASVmZD869S_5jJzFVIlGjE4GWh5KolDP2WN002aNaOfrptUSvEdUXM0EaD2
MWdl0HtyyI8bPA1Xo3FxMEjukd7MmjrhZ4CbFws6XF82A7Jmt5k$>           Meeting ID:
968 6712 1232     Join by Telephone      For higher quality, dial a number based
on your current location.       Dial:  +1 309 205 3325 US +1 312 626 6799 US
(Chicago) +1 301 715 8592 US (Washington DC) +1 305 224 1968 US +1 646 931 3860
US +1 929 436 2866 US (New York) +1 689 278 1000 US +1 719 359 4580 US +1 253
205 0468 US +1 253 215 8782 US (Tacoma) +1 346 248 7799 US (Houston) +1 360 209
5623 US +1 386 347 5053 US +1 507 473 4847 US +1 564 217 2000 US +1 669 444 9171
US +1 669 900 6833 US (San Jose)    Meeting ID:    968 6712 1232
International numbers <https://urldefense.com/v3/__https://northwestern.zoom.us/
u/a8l2pMmL9__;!!Dq0X2DkFhyF93HkjWTBQKhk!S5Ji2liQrASVmZD869S_5jJzFVIlGjE4GWh5KolD
P2WN002aNaOfrptUSvEdUXM0EaD2MWdl0HtyyI8bPA1Xo3FxMEjukd7MmjrhZ4CbFws6XF82i6k6_sw$
>       Join from an H.323/SIP room system     H.323:         144.195.19.161 (US
West) 206.247.11.121 (US East) 221.122.88.195 (Mainland China) 115.114.131.7
(India Mumbai) 115.114.115.7 (India Hyderabad) 159.124.15.191 (Amsterdam
Netherlands) 159.124.47.249 (Germany) 159.124.104.213 (Australia Sydney)
159.124.74.212 (Australia Melbourne) 170.114.134.121 (Hong Kong SAR)
170.114.180.219 (Singapore) 64.211.144.160 (Brazil) 159.124.132.243 (Mexico)
159.124.168.213 (Canada Toronto) 159.124.196.25 (Canada Vancouver)
170.114.194.163 (Japan Tokyo) 147.124.100.25 (Japan Osaka)        Meeting ID:
968 6712 1232     SIP:  96867121232@zoomcrc.com
________________________________   Access the BLOCK-STAFF Home Page and Archives
<https://LISTSERV.IT.NORTHWESTERN.EDU/cgi-bin/wa.exe?A0=BLOCK-STAFF>
Unsubscribe from the BLOCK-STAFF List <https://LISTSERV.IT.NORTHWESTERN.EDU/cgi-
bin/wa.exe?TICKET=NzM5NjYxIHJvY2lvLm9sYXNpbWJvQE5PUlRIV0VTVEVSTi5FRFUgQkxPQ0stU1
RBRkYgIBFuknUwp5md&c=SIGNOFF>

--- Row 21 ---
Date: 02/11/2026  Time: 1:00PM-1:45 PM  Type of Event: Class visit  Name of
Group: ART_HIST 330: Renaissance Worlds  Location: Katz Classroom  Internal
Contact Person(s): Essi Rönkkö  External Contact Person(s): Laura Rybicki
<LauraRybicki2030@u.northwestern.edu
<mailto:LauraRybicki2030@u.northwestern.edu> >, Rebecca Zorach
<rebecca.zorach@northwestern.edu>  Guests Expected: 1-2  Taking Attendance
(Y/N): Y  Attendance Total:  Notes:

--- Row 22 ---
Date: Every Wednesday from 3-5pm  Time: 2:15PM-5:15PM  Type of Event: Reception
Name of Group: Living Room Weekly Coffee   Location: Block lobby   Internal
Contact Person(s): Erin and Chris  External Contact Person(s):  N/A  Guests
Expected: N/A  Taking Attendance (Y/N): N  Attendance Total:   Notes: VS –
please set up an 8 ft table near the magazine rack each Wednesday by 2:15pm.
Compass Catering will drop off coffee/tea service and a linen between
2:30-2:45pm, and return to pick this up at 5:00pm. VS, please also take away the
bars and leave in the Engagement office (we will not serve these to the public)
We will not serve coffee on Wed Mar 25 (Spring Break). We will have an extra
Living Room coffee on Thurs, Jan 22 from 3-5pm in addition to the weekly coffee
on Wed, Jan 21.   The last coffee of Spring Quarter will be on Wed, Apr 1; the
Living Room will close on Sun, Apr 12. Contact Chris or Erin with questions.

--- Row 23 ---
Date: 02/11/2026  Time: 4:00PM-5:30PM  Type of Event: BMSA-led tour  Name of
Group: Atlas Mentorship, Buffett Institute for Global Affairs  Location: Living
room, main gallery    Internal Contact Person(s): Ethan  External Contact
Person(s): Renato de Souza Elisanio  Guests Expected: 20   Taking Attendance
(Y/N): Y   Attendance Total:  Notes: BMSA-led. 773-739-1445 if you need to reach
Renato (BMSA that will be leading the tour).

--- Row 24 ---
Date: 02/12/26   Time: 12:30-1:30PM  Type of Event: Public Program  Name of
Group: Curator Talk: Hamdia Traoré from Kathleen   Location: main gallery
Internal Contact Person(s): Margaret, Isabella, Erin  External Contact
Person(s):  N/A  Guests Expected: TBD    Taking Attendance (Y/N): Y  Attendance
Total:

--- Row 25 ---
Date: 02/12/2026  Time: 1:00PM-2:20 PM  Type of Event: Class visit  Name of
Group: ATP 101: On Seeing and Believing  Location: Katz Classroom  Internal
Contact Person(s): Essi Rönkkö  External Contact Person(s): Pamela L Bannos
<pbannos@northwestern.edu>  Guests Expected: 14  Taking Attendance (Y/N): Y
Attendance Total:  Notes: Please have bins available in the lobby.

--- Row 26 ---
Date: 02/12/2026  Time: 3:00PM-4:00 PM  Type of Event: Research visit  Name of
Group: Prof. Matos  Location: Katz Classroom  Internal Contact Person(s): Essi
External Contact Person(s): Dr. Rafael O. Matos <rafael.matos@northwestern.edu>
Guests Expected: `1  Taking Attendance (Y/N): Y  Attendance Total:

--- Row 27 ---
Date: 2/12/2026  Time: 4:00-5:30pm  Type of Event: Cur-led Tour   Name of Group:
Art History undergraduate meet up  Location: Lobby, Galleries  Internal Contact
Person(s): Erin, Kathleen, Corinne   External Contact Person(s): Caitlin Burney,
caitlin.kelley@northwestern.edu <mailto:caitlin.kelley@northwestern.edu>
Guests Expected: 20  Taking Attendance(Y/N): Y  Attendance Total:  Notes: Social
meet up for Art History undergraduates and faculty; Kathleen and Corinne will
greet/welcome and offer a tour of the main exhibitions. Art History will have
coffee/cider and cookies dropped off to the Block lobby through Compass catering
between 3:30-3:45pm; Caitlin Burney will return at 5:30pm to ensure everything
is cleaned up; Visitor Services, please set up a table in the lobby where we
have our usual Living Room coffee set up for their cookies/drinks by 3:30pm with
a black linen.

--- Row 28 ---
Date: 02/12/2026  Time: 6:30-7:30pm  Type of Event: Campus/co-curricular visit
Name of Group: NU Athletics  Location: Katz Classroom  Internal Contact
Person(s): Erin Northington   External Contact Person(s): Maria Elena Sanchez
maria.sanchez@northwestern.edu <mailto:maria.sanchez@northwestern.edu>   Guests
Expected: 4-8  Taking Attendance (Y/N): Y  Attendance Total:  Notes: Please have
bins available in the lobby.

--- Row 29 ---
Date: 02/13/2026  Time: 9:00AM-1:00 PM  Type of Event: Class visit  Name of
Group: ART_HIST 232:  Introduction to the History of Architecture  Location:
Katz Classroom  Internal Contact Person(s): Essi Rönkkö  External Contact
Person(s): Hollyamber Kennedy <hollyamber.kennedy@northwestern.edu>  Guests
Expected: 16  Taking Attendance (Y/N): Y  Attendance Total:  Notes: Please have
bins available in the lobby. NOTE: This reservation consists of a series of four
sections:  9:00-9:50  10:00-10:50 11:00-11:50  12:00-12:50

In [57]:
for idx, desc in enumerate(df['Subject'].head()):
    print(f"--- Row {idx} ---")
    print(textwrap.fill(desc, width=80))
    print()

--- Row 0 ---
AMER_ST 310: The Military-Industrial Complex

--- Row 1 ---
All Staff Meeting (Winter 2026)

--- Row 2 ---
Self Guided: ENG 105: Who Are Museums For?

--- Row 3 ---
AH 403 student visit

--- Row 4 ---
Living Room Weekly Coffee

In [68]:
for idx, desc in enumerate(df['Location'].head()):
    print(f"--- Row {idx} ---")
    print(textwrap.fill(desc, width=80))
    print()

--- Row 0 ---
Katz classroom

--- Row 1 ---
https://northwestern.zoom.us/j/96867121232?from=addon

--- Row 2 ---
All galleries

--- Row 3 ---
Katz classroom

--- Row 4 ---
Block lobby

In [55]:
print(df.loc[0, 'Description'])

Date: 02/05/2026  Time: 3:30PM-4:50 PM  Type of Event: Class visit  Name of Group: BLCK_ST_101: Fighting Apartheid, Locally and Globally  Location: Katz Classroom  Internal Contact Person(s): Essi  External Contact Person(s): Martha Biondi <m-biondi@northwestern.edu>  Guests Expected: TBD (likely 16)  Taking Attendance (Y/N): Y  Attendance Total:  Notes: Please have bins available in the lobby.

In [ ]:
# need to eliminate all rows that start with "Canceled" and "AUTOMATED"

In [33]:
doc = Document()
current_date = None

for _, row in df.iterrows():
    if row['date_str'] != current_date:
        current_data = row['date_str']
        doc.add_heading(current_date, level=1)

    p = doc.add_paragraph()
    run = p.add_run(row['time_str'] + ' | ')
    run.bold = True
    p.add_run(row['Subject'])

    line = f"{row['time_str']} | {row['Subject']}"
    doc.add_paragraph(line)

    if pd.notna(row['Location']):
        doc.add_paragraph(f"Location: {row['Location']}", style='Intense Quote')
    
    if pd.notna(row['Description']):
        doc.add_paragraph(f"Description: {row['Description']}", style='Intense Quote')

doc.save('temp.docx')